### ISSUE TITLE
User Calendar not working since version 1.0.16

### ISSUE THREAD

**Issue by Andiministrator** [fguillot/kanboard#1040]
Since the update to Kanboard 1.0.16 our internal calendar view (of a kanboard user) is empty. It worked fine before.

**Comment by fguillot** [comment]
Yes, it was fixed in the development version.

**Comment by Andiministrator** [comment]
Unfortunately the bug still exists in Kanboard 1.0.17.
The calendars of the boards are working but not the user calendars.

**Comment by fguillot** [comment]
It's working for me, I also tested with the online demo, can you describe what is not working exactly in user calendar? How can I reproduce your issue?

**Comment by Andiministrator** [comment]
Lets explain it with screenshots:

This is the calendar of a project board:
![29-07-_2015_09-39-58](https://cloud.githubusercontent.com/assets/355946/8952299/0e16c38e-35d6-11e5-819a-d6717858f39a.png)

And this is my user calendar, which is empty:
![29-07-_2015_09-40-21](https://cloud.githubusercontent.com/assets/355946/8952309/1e99087a-35d6-11e5-9100-9ddf8bac0d01.png)

When I create a date for an existing task, the task appears in the project calendar, but not in the user calendar (where I can normally see all of my tasks - from all projects - together).

**Comment by fguillot** [comment]
Only tasks assigned to you will appear in your user calendar, is it the case?

**Comment by Andiministrator** [comment]
Yes, the tasks from the first screen are all assigned to me.

**Comment by Andiministrator** [comment]
I'm using Kanboard with MySQL, could the problem come from there (maybe changes of a table structure)?

**Comment by fguillot** [comment]
Even with my myql, I didn't reproduce the problem.

**Comment by Rogieee** [comment]
Does your time slot allocation also not work?

**Comment by Andiministrator** [comment]
This works. Even the access over iCal works fine.
Its just the internal calendar, which is not working.
Let me try to reinstall the Board ...

**Comment by Andiministrator** [comment]
So, I installed Kanboard in a second directory and tried to reproduce the problem.
The calendar worked (also with MySQL) up to I changed Kanboard from a subdirectory to a subdomain.
It works with http://mydomain.de/kanboard/
but not with http://kanboard.mydomain.de/

I hope this helps ...

**Comment by Andiministrator** [comment]
Update: Even if I change (back to the subdirectory) - my taks will not appear in my user calendar. The project calendar works fine ...

**Comment by Andiministrator** [comment]
Update: I don't know why, but today the user calendar is working again (overnight).
