### ISSUE TITLE
Duplicate a task from a another project

### ISSUE THREAD

**Issue by pconstans** [fguillot/kanboard#585]
Hi,

We have just upgrade "kanboard" (1.0.9 -> 1.0.10).
We face up to a problem when we want to duplicate a task from a project to another one.

1.0.9 >
![050215 - kanboard0021](https://cloud.githubusercontent.com/assets/10863849/6058996/33a8ca5c-ad2d-11e4-83ef-227eabbee16d.jpg)

1.0.10 >
![050215 - kanboard001](https://cloud.githubusercontent.com/assets/10863849/6058999/41133088-ad2d-11e4-8e97-622ba24112c7.jpg)

A automated action will not work too.

The rest seems to work fine.

What is the problem ? The solution ?

Regards.

**Comment by BlueTeck** [comment]
In the current dev version some things about the duplication were fixed.

**Comment by pconstans** [comment]
Sorry, our version is 1.0.11 not 1.0.10. So the problem persists...

**Comment by fguillot** [comment]
@pconstans The dropdown menu display only projects where you are member. You have to be member of the project, go to project settings then user management and add your user.

**Comment by pconstans** [comment]
I am administrator. I can access to all projects and more.

Details :
I upgraded kanboard from 10.0.11 to 10.1.0.12. No change.
I can create new projects and tasks. I can duplicate tasks from a new project to another new project. Not to an old project. As there is a lock somewhere.
